import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { mlRulesApi } from '../api/mlRules'
import { useAuthStore } from '../store/authStore'
import { TopBar } from '../components/layout/TopBar'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import toast from 'react-hot-toast'
import { MLPendingRule } from '../types'
import { Sparkles, Check, X, Clock, AlertTriangle, Code, Trash2, ShieldCheck, RefreshCw } from 'lucide-react'

export const MLRules: React.FC = () => {
  const { user } = useAuthStore()
  const isAdmin = user?.role === 'admin'
  const queryClient = useQueryClient()
  const [activeTab, setActiveTab] = useState<'pending' | 'approved' | 'rejected'>('pending')
  const [rejectReason, setRejectReason] = useState('')
  const [rejectingId, setRejectingId] = useState<string | null>(null)

  const { data: rules = [], isLoading, refetch } = useQuery({
    queryKey: ['ml-rules', activeTab],
    queryFn: () => mlRulesApi.listRules(activeTab),
    refetchInterval: 10000,
  })

  const approveMutation = useMutation({
    mutationFn: (id: string) => mlRulesApi.approveRule(id),
    onSuccess: () => {
      toast.success('ML Rule approved and deployed to ModSecurity!')
      queryClient.invalidateQueries({ queryKey: ['ml-rules'] })
    },
    onError: (err: any) => toast.error(err.response?.data?.detail || 'Failed to approve rule'),
  })

  const rejectMutation = useMutation({
    mutationFn: ({ id, reason }: { id: string; reason: string }) => mlRulesApi.rejectRule(id, reason),
    onSuccess: () => {
      toast.success('Rule marked as rejected')
      setRejectingId(null)
      setRejectReason('')
      queryClient.invalidateQueries({ queryKey: ['ml-rules'] })
    },
    onError: (err: any) => toast.error(err.response?.data?.detail || 'Failed to reject rule'),
  })

  const handleApprove = (id: string) => {
    if (!isAdmin) {
      toast.error('Administrator privileges required to approve and deploy rules')
      return
    }
    approveMutation.mutate(id)
  }

  const handleReject = (id: string) => {
    if (!isAdmin) {
      toast.error('Administrator privileges required to reject rules')
      return
    }
    rejectMutation.mutate({ id, reason: rejectReason })
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <TopBar
        title="ML Anomaly Rule Approvals"
        subtitle="Review, approve, and hot-deploy SecRule definitions generated by the AI classifier"
        badge={
          <Badge color="purple" dot>
            AI COPILOT
          </Badge>
        }
        action={
          <div className="flex rounded-lg border border-[var(--bg-border)] bg-[var(--bg-surface)] p-0.5 font-mono text-[12px]">
            {(['pending', 'approved', 'rejected'] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-3 py-1 font-semibold rounded-md transition-all capitalize cursor-pointer ${
                  activeTab === tab
                    ? 'bg-violet-600 text-white shadow-sm'
                    : 'text-[var(--text-secondary)] hover:text-[var(--text-primary)]'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
        }
      />

      <div className="space-y-4">
        {isLoading && (
          <div className="text-center py-12 text-[var(--text-muted)] font-mono text-[12px]">
            <RefreshCw size={16} className="animate-spin inline mr-2 text-violet-500" />
            Loading ML rule queues...
          </div>
        )}

        {!isLoading && rules.length === 0 && (
          <div className="dash-card p-12 text-center space-y-2">
            <Sparkles size={36} className="mx-auto text-violet-400 opacity-40" />
            <h3 className="text-[14px] font-bold text-[var(--text-primary)] font-mono m-0">
              No {activeTab} rules
            </h3>
            <p className="text-[12px] text-[var(--text-muted)] m-0 font-mono">
              {activeTab === 'pending'
                ? 'All AI-suggested rules have been processed or none have been generated recently.'
                : `There are currently no rules categorized as ${activeTab}.`}
            </p>
          </div>
        )}

        {rules.map((rule) => (
          <div key={rule.rule_id} className="dash-card overflow-hidden">
            {/* Status Accent Bar */}
            <div
              className={`h-1 w-full ${
                rule.status === 'pending'
                  ? 'bg-amber-500'
                  : rule.status === 'approved'
                  ? 'bg-emerald-500'
                  : 'bg-red-500'
              }`}
            />

            <div className="p-5 sm:p-6 space-y-4">
              <div className="flex justify-between items-start flex-wrap gap-3">
                <div className="flex items-center gap-3">
                  <div
                    className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                      rule.status === 'pending'
                        ? 'bg-amber-500/15 text-amber-500'
                        : rule.status === 'approved'
                        ? 'bg-emerald-500/15 text-emerald-500'
                        : 'bg-red-500/15 text-red-500'
                    }`}
                  >
                    {rule.status === 'pending' ? (
                      <Clock size={18} />
                    ) : rule.status === 'approved' ? (
                      <Check size={18} />
                    ) : (
                      <X size={18} />
                    )}
                  </div>
                  <div>
                    <h3 className="text-[15px] font-bold text-[var(--text-primary)] font-mono flex items-center gap-2 m-0">
                      <Sparkles size={14} className="text-violet-400" />
                      {rule.attack_type}
                    </h3>
                    <p className="text-[11.5px] text-[var(--text-muted)] font-mono m-0 mt-0.5">
                      Suggested: {new Date(rule.created_at).toLocaleString()}
                    </p>
                  </div>
                </div>

                <div>
                  {rule.status === 'pending' && <Badge color="warning" dot>PENDING APPROVAL</Badge>}
                  {rule.status === 'approved' && (
                    <Badge color="success" dot>
                      DEPLOYED #{rule.deployed_rule_id}
                    </Badge>
                  )}
                  {rule.status === 'rejected' && <Badge color="danger" dot>REJECTED</Badge>}
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="space-y-3 font-mono text-[12px]">
                  <div className="p-3.5 rounded-lg bg-[var(--bg-primary)] border border-[var(--bg-border)]">
                    <span className="text-[10px] font-bold uppercase text-[var(--text-muted)] block mb-1">
                      Matched Target & Pattern
                    </span>
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <span className="text-[11px] text-[var(--text-muted)] block">Pattern</span>
                        <span className="font-bold text-violet-400 break-all">{rule.pattern}</span>
                      </div>
                      <div>
                        <span className="text-[11px] text-[var(--text-muted)] block">Variable</span>
                        <span className="text-[var(--text-primary)]">{rule.variable}</span>
                      </div>
                    </div>
                  </div>

                  <div className="p-3.5 rounded-lg bg-[var(--bg-primary)] border border-[var(--bg-border)]">
                    <span className="text-[10px] font-bold uppercase text-[var(--text-muted)] block mb-1">
                      Source Request
                    </span>
                    <div className="flex items-center gap-2">
                      <Badge color="gray">{rule.source_method}</Badge>
                      <span className="text-[var(--text-primary)] truncate">{rule.source_url}</span>
                    </div>
                  </div>
                </div>

                {/* SecRule Preview */}
                <div className="rounded-lg bg-[var(--bg-primary)] border border-[var(--bg-border)] overflow-hidden flex flex-col font-mono text-[11.5px]">
                  <div className="px-3 py-2 bg-[var(--bg-surface-elevated)] border-b border-[var(--bg-border)] flex items-center gap-2">
                    <Code size={13} className="text-violet-400" />
                    <span className="font-bold uppercase text-[10px] text-[var(--text-muted)]">
                      Generated SecRule Preview
                    </span>
                  </div>
                  <div className="p-3.5 overflow-x-auto text-violet-300 flex-1 leading-relaxed">
                    <pre className="m-0">
                      {rule.secrule_template.replace(
                        '{RULE_ID}',
                        rule.deployed_rule_id ? String(rule.deployed_rule_id) : 'PENDING_ID'
                      )}
                    </pre>
                  </div>
                </div>
              </div>

              {/* Action Buttons for Pending */}
              {rule.status === 'pending' && isAdmin && (
                <div className="flex items-center gap-3 pt-3 border-t border-[var(--bg-border)]">
                  {rejectingId === rule.rule_id ? (
                    <div className="flex-1 flex gap-2 animate-fade-in">
                      <input
                        type="text"
                        placeholder="Specify reason for rejection (optional)..."
                        value={rejectReason}
                        onChange={(e) => setRejectReason(e.target.value)}
                        className="flex-1 dash-input text-[12px] font-mono"
                        autoFocus
                      />
                      <Button
                        variant="danger"
                        onClick={() => handleReject(rule.rule_id)}
                        isLoading={rejectMutation.isPending}
                      >
                        Confirm Reject
                      </Button>
                      <Button
                        variant="ghost"
                        onClick={() => {
                          setRejectingId(null)
                          setRejectReason('')
                        }}
                      >
                        Cancel
                      </Button>
                    </div>
                  ) : (
                    <div className="flex-1 flex gap-2 justify-end">
                      <Button
                        variant="danger"
                        onClick={() => setRejectingId(rule.rule_id)}
                        icon={<X size={14} />}
                      >
                        Reject
                      </Button>
                      <Button
                        variant="success"
                        onClick={() => handleApprove(rule.rule_id)}
                        isLoading={approveMutation.isPending}
                        icon={<Check size={14} />}
                      >
                        Approve & Deploy to ModSec
                      </Button>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default MLRules
