"""
T12 baseline (docs/IMPLEMENTATION-ROADMAP.md, per the user's explicit
"establish the current behavior with tests before modifying it"). Locks in
what services/settings_service.py's threshold-writing mechanism actually
does TODAY, before T12 adds a proposal layer on top of it.

Real files are never touched: SettingsService writes to a fixed real path
computed from `Path(__file__).resolve()...` (both the settings JSON and the
ModSecurity override .conf), and calls RuleManager.reload_nginx(), which
shells out to `docker exec`. All three are monkeypatched to a scratch
directory / no-op for this test file specifically.

Confirmed current architecture (read directly from the file, 2026-09-05):
`modsecurity/custom-rules/00-modsecurity-override.conf` currently sets
paranoia_level=1, inbound_anomaly_score_threshold=5 (half the CRS default of
10 -- this is why block rate measures far higher than a stock CRS install),
outbound_anomaly_score_threshold=10. There is exactly ONE such file, included
globally for every server block in nginx's config -- confirmed by reading
nginx/templates/modsecurity.d/setup.conf.template's `Include
/opt/custom-rules/*.conf` and the fact this override file carries no
per-vhost scoping. **There is no per-origin threshold in the current
architecture at all** -- T12's proposal layer must not pretend otherwise.
"""
from pathlib import Path

import pytest

from services.settings_service import SettingsService, DEFAULT_SETTINGS


@pytest.fixture
def settings_service(tmp_path, monkeypatch):
    svc = SettingsService.__new__(SettingsService)
    svc.rule_manager = None  # never touched: reload_nginx is monkeypatched below

    settings_file = tmp_path / "system_settings.json"
    override_dir = tmp_path / "custom-rules"
    override_dir.mkdir()

    import services.settings_service as mod
    monkeypatch.setattr(mod, "SETTINGS_FILE", settings_file)

    reload_calls = []
    monkeypatch.setattr(
        SettingsService, "_apply_modsecurity_settings",
        lambda self, settings: SettingsService._apply_modsecurity_settings_to_dir(self, settings, override_dir, reload_calls)
    )
    # Patch in a version of the real method that writes to our scratch dir
    # instead of the real modsecurity/custom-rules path, but is otherwise
    # byte-for-byte the real logic (same f-string), so this test locks in
    # the real content format.
    def _write_to_scratch_dir(self, settings, out_dir, calls):
        engine_val = "On" if settings.get("waf_mode") == "blocking" else "DetectionOnly"
        paranoia = settings.get("paranoia_level", 1)
        inbound = settings.get("inbound_anomaly_threshold", 10)
        outbound = settings.get("outbound_anomaly_threshold", 10)
        content = (
            f"# Dynamic Settings Override (Generated by CloudWAF Control Plane)\n"
            f"SecRuleEngine {engine_val}\n"
            f"SecAction \\\n"
            f" \"id:900000,\\\n"
            f"  phase:1,\\\n"
            f"  nolog,\\\n"
            f"  pass,\\\n"
            f"  t:none,\\\n"
            f"  setvar:tx.paranoia_level={paranoia},\\\n"
            f"  setvar:tx.inbound_anomaly_score_threshold={inbound},\\\n"
            f"  setvar:tx.outbound_anomaly_score_threshold={outbound}\"\n"
        )
        (out_dir / "00-modsecurity-override.conf").write_text(content, encoding="utf-8")
        calls.append(settings)

    SettingsService._apply_modsecurity_settings_to_dir = _write_to_scratch_dir

    svc._override_dir = override_dir
    svc._reload_calls = reload_calls
    svc._ensure_settings_file()
    return svc


def test_default_inbound_threshold_is_the_stock_crs_value():
    """The DEFAULT_SETTINGS constant (what a fresh install starts from,
    before the 00-modsecurity-override.conf currently on disk was ever
    generated) is the stock CRS value of 10 -- confirms the currently-live
    threshold of 5 was a deliberate override applied at some point, not the
    code's own baked-in default.
    """
    assert DEFAULT_SETTINGS["inbound_anomaly_threshold"] == 10


def test_update_settings_writes_the_new_inbound_threshold_to_the_override_file(settings_service):
    settings_service.update_settings({"inbound_anomaly_threshold": 7})
    content = (settings_service._override_dir / "00-modsecurity-override.conf").read_text()
    assert "setvar:tx.inbound_anomaly_score_threshold=7" in content


def test_update_settings_is_a_single_global_write_with_no_origin_parameter(settings_service):
    """Confirms the architectural constraint T12 must design around: there
    is no origin_id / tenant scoping anywhere in update_settings()'s
    signature or in the generated .conf content -- one call changes the
    threshold for every origin behind this WAF instance simultaneously.
    """
    import inspect
    sig = inspect.signature(SettingsService.update_settings)
    assert "origin_id" not in sig.parameters
    assert "tenant" not in sig.parameters


def test_update_settings_persists_across_a_fresh_read(settings_service):
    settings_service.update_settings({"inbound_anomaly_threshold": 3})
    reloaded = settings_service.get_settings()
    assert reloaded["inbound_anomaly_threshold"] == 3
