services:
  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf-nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx/templates/conf.d/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro
      - ./nginx/templates/modsecurity.d/setup.conf.template:/etc/nginx/templates/modsecurity.d/setup.conf.template:ro
      - ./modsecurity/custom-rules:/opt/custom-rules:ro
    environment:
      PARANOIA: 1
      ANOMALY_INBOUND: 10
      ANOMALY_OUTBOUND: 10
    restart: unless-stopped
    networks:
      - waf-net

networks:
  waf-net:
    driver: bridge
