import os
import time
import sqlite3
import re
import ipaddress
import logging
from pathlib import Path
from typing import List, Dict, Optional
from services.rule_manager import RuleManager

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
DB_PATH = DATA_DIR / "ip_rules.db"

CUSTOM_RULES_DIR = Path(__file__).resolve().parent.parent.parent.parent / "modsecurity" / "custom-rules"
CUSTOM_RULES_DIR.mkdir(parents=True, exist_ok=True)

BLOCKLIST_TXT = CUSTOM_RULES_DIR / "global_blocklist.txt"
WHITELIST_TXT = CUSTOM_RULES_DIR / "global_whitelist.txt"
BLOCKLIST_CONF = CUSTOM_RULES_DIR / "custom-000000-global-blocklist.conf"
WHITELIST_CONF = CUSTOM_RULES_DIR / "custom-000001-global-whitelist.conf"


class IPRuleService:
    def __init__(self):
        self._init_db()
        self.rule_manager = RuleManager()
        self._sync_files_from_db()

    def _get_conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self):
        conn = self._get_conn()
        try:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS ip_rules (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ip TEXT NOT NULL UNIQUE,
                    rule_type TEXT NOT NULL DEFAULT 'block',  -- 'block' or 'allow'
                    reason TEXT NOT NULL DEFAULT 'Manual entry',
                    added_by TEXT NOT NULL DEFAULT 'admin',
                    created_at INTEGER NOT NULL,
                    expires_at INTEGER DEFAULT NULL,         -- NULL means Permanent
                    hits INTEGER NOT NULL DEFAULT 0,
                    source TEXT NOT NULL DEFAULT 'manual'   -- 'manual', 'ml_analyst', 'rate_limit'
                )
            """)
            conn.commit()
        finally:
            conn.close()

    def _validate_ip_or_cidr(self, ip_str: str) -> str:
        ip_str = ip_str.strip()
        try:
            if "/" in ip_str:
                network = ipaddress.ip_network(ip_str, strict=False)
                return str(network)
            else:
                ip_obj = ipaddress.ip_address(ip_str)
                return str(ip_obj)
        except ValueError:
            raise ValueError(f"Invalid IP address or CIDR notation: '{ip_str}'")

    def _sync_files_from_db(self):
        """Re-generate global_blocklist.txt, global_whitelist.txt and the corresponding ModSec .conf files."""
        now = int(time.time())
        conn = self._get_conn()
        try:
            # Delete expired entries
            conn.execute("DELETE FROM ip_rules WHERE expires_at IS NOT NULL AND expires_at < ?", (now,))
            conn.commit()

            # Query active blocklist
            blocked_rows = conn.execute("SELECT ip FROM ip_rules WHERE rule_type = 'block' ORDER BY created_at DESC").fetchall()
            blocked_ips = [r["ip"] for r in blocked_rows if r["ip"]]

            # Query active whitelist
            allowed_rows = conn.execute("SELECT ip FROM ip_rules WHERE rule_type = 'allow' ORDER BY created_at DESC").fetchall()
            allowed_ips = [r["ip"] for r in allowed_rows if r["ip"]]
        finally:
            conn.close()

        # 1. Write Blocklist Text
        BLOCKLIST_TXT.write_text("\n".join(blocked_ips) + ("\n" if blocked_ips else ""), encoding="utf-8")
        if blocked_ips:
            BLOCKLIST_CONF.write_text(
                "# Global Blocklist Rule (Auto-generated by CloudWAF)\n"
                "SecRule REMOTE_ADDR|REQUEST_HEADERS:X-Real-IP \"@ipMatchFromFile /opt/custom-rules/global_blocklist.txt\" \\\n"
                "    \"id:1000000,phase:1,deny,status:403,log,msg:'Global IP Blocklist: Connection Dropped'\"\n",
                encoding="utf-8"
            )
        else:
            # Remove or clear conf file if no blocked IPs to avoid error
            if BLOCKLIST_CONF.exists():
                BLOCKLIST_CONF.unlink()

        # 2. Write Whitelist Text
        WHITELIST_TXT.write_text("\n".join(allowed_ips) + ("\n" if allowed_ips else ""), encoding="utf-8")
        if allowed_ips:
            WHITELIST_CONF.write_text(
                "# Global Whitelist Rule (Auto-generated by CloudWAF)\n"
                "SecRule REMOTE_ADDR|REQUEST_HEADERS:X-Real-IP \"@ipMatchFromFile /opt/custom-rules/global_whitelist.txt\" \\\n"
                "    \"id:1000001,phase:1,allow,nolog,msg:'Global IP Whitelist: Bypass WAF'\"\n",
                encoding="utf-8"
            )
        else:
            if WHITELIST_CONF.exists():
                WHITELIST_CONF.unlink()

    def list_rules(self, rule_type: Optional[str] = None, search: Optional[str] = None) -> List[Dict]:
        self._sync_files_from_db()
        conn = self._get_conn()
        try:
            query = "SELECT * FROM ip_rules WHERE 1=1"
            params = []

            if rule_type and rule_type.lower() != 'all':
                query += " AND rule_type = ?"
                params.append(rule_type.lower())

            if search:
                query += " AND (ip LIKE ? OR reason LIKE ? OR added_by LIKE ?)"
                search_param = f"%{search.strip()}%"
                params.extend([search_param, search_param, search_param])

            query += " ORDER BY created_at DESC"
            rows = conn.execute(query, params).fetchall()

            now = int(time.time())
            result = []
            for r in rows:
                item = dict(r)
                if item["expires_at"]:
                    remaining = item["expires_at"] - now
                    item["remaining_seconds"] = max(0, remaining)
                else:
                    item["remaining_seconds"] = None
                result.append(item)
            return result
        finally:
            conn.close()

    def add_rule(self, ip: str, rule_type: str = "block", reason: str = "Manual entry",
                 added_by: str = "admin", duration_seconds: Optional[int] = None, source: str = "manual") -> Dict:
        validated_ip = self._validate_ip_or_cidr(ip)
        rule_type = rule_type.lower()
        if rule_type not in ["block", "allow"]:
            raise ValueError("rule_type must be 'block' or 'allow'")

        now = int(time.time())
        expires_at = (now + duration_seconds) if (duration_seconds and duration_seconds > 0) else None

        conn = self._get_conn()
        try:
            conn.execute("""
                INSERT OR REPLACE INTO ip_rules (ip, rule_type, reason, added_by, created_at, expires_at, source)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (validated_ip, rule_type, reason.strip()[:200], added_by[:64], now, expires_at, source[:32]))
            conn.commit()
        finally:
            conn.close()

        self._sync_files_from_db()
        try:
            self.rule_manager.reload_nginx()
        except Exception as e:
            logger.warning(f"Nginx reload notification skipped: {e}")

        return {
            "status": "success",
            "ip": validated_ip,
            "rule_type": rule_type,
            "expires_at": expires_at
        }

    def delete_rule(self, ip: str) -> bool:
        ip = ip.strip()
        conn = self._get_conn()
        try:
            cursor = conn.execute("DELETE FROM ip_rules WHERE ip = ?", (ip,))
            conn.commit()
            deleted = cursor.rowcount > 0
        finally:
            conn.close()

        if deleted:
            self._sync_files_from_db()
            try:
                self.rule_manager.reload_nginx()
            except Exception as e:
                logger.warning(f"Nginx reload notification skipped: {e}")
        return deleted

    def bulk_delete(self, ips: List[str]) -> int:
        if not ips:
            return 0
        conn = self._get_conn()
        try:
            placeholders = ",".join("?" for _ in ips)
            cursor = conn.execute(f"DELETE FROM ip_rules WHERE ip IN ({placeholders})", ips)
            conn.commit()
            deleted_count = cursor.rowcount
        finally:
            conn.close()

        if deleted_count > 0:
            self._sync_files_from_db()
            try:
                self.rule_manager.reload_nginx()
            except Exception as e:
                logger.warning(f"Nginx reload notification skipped: {e}")
        return deleted_count

    def get_stats(self) -> Dict:
        conn = self._get_conn()
        try:
            total_blocked = conn.execute("SELECT COUNT(*) FROM ip_rules WHERE rule_type = 'block'").fetchone()[0]
            total_allowed = conn.execute("SELECT COUNT(*) FROM ip_rules WHERE rule_type = 'allow'").fetchone()[0]
            temp_banned = conn.execute("SELECT COUNT(*) FROM ip_rules WHERE rule_type = 'block' AND expires_at IS NOT NULL").fetchone()[0]
            return {
                "total_blocked": total_blocked,
                "total_allowed": total_allowed,
                "temp_banned": temp_banned,
                "permanent_blocked": total_blocked - temp_banned
            }
        finally:
            conn.close()
