import os
import re
import ipaddress
import logging
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any, List

from services.dynamodb_service import DynamoDBService
from services.rule_manager import RuleManager, CONTAINER_NAME

logger = logging.getLogger(__name__)

db = DynamoDBService()
rule_mgr = RuleManager()

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PERSISTENT_SITES_DIR = BASE_DIR / "nginx" / "custom_sites"
PERSISTENT_SITES_DIR.mkdir(parents=True, exist_ok=True)


# Everything below is written into an nginx config file and used as a file name
# inside the nginx container, so it is validated here rather than trusted from
# the caller: a newline or ";" in a value would add nginx directives, and a "/"
# or ".." in the domain would write outside conf.d.
_HOSTNAME_RE = re.compile(r"^(?=.{1,253}$)(?!-)[a-z0-9-]{1,63}(?<!-)(\.(?!-)[a-z0-9-]{1,63}(?<!-))+$")


def _safe_domain(domain_name: str) -> str:
    domain = str(domain_name or "").strip().lower().rstrip(".")
    if not _HOSTNAME_RE.match(domain):
        raise ValueError(f"invalid domain name: {domain_name!r}")
    return domain


def _safe_upstream(origin: Dict[str, Any]) -> tuple:
    ip_or_host = str(origin.get("ip", "")).strip().lower()
    try:
        ipaddress.ip_address(ip_or_host)
    except ValueError:
        if not _HOSTNAME_RE.match(ip_or_host):
            raise ValueError(f"invalid origin address: {origin.get('ip')!r}")
    try:
        port = int(origin.get("port", 80))
    except (TypeError, ValueError):
        raise ValueError(f"invalid origin port: {origin.get('port')!r}")
    if not 1 <= port <= 65535:
        raise ValueError(f"invalid origin port: {port}")
    return ip_or_host, port


def generate_site_nginx_config(domain_name: str, origin: Dict[str, Any]) -> str:
    domain = _safe_domain(domain_name)
    ip_or_host, port = _safe_upstream(origin)

    # Check if origin is HTTPS (Port 443 or FQDN on HTTPS)
    is_https = (port == 443) or (not ip_or_host.replace(".", "").isdigit() and port == 443)

    if is_https:
        upstream_target = f"https://{ip_or_host}"
        host_header = ip_or_host
        ssl_directives = """        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
        proxy_set_header X-Forwarded-Proto https;"""
    else:
        upstream_target = f"http://{ip_or_host}:{port}"
        host_header = "$host"
        ssl_directives = """        proxy_set_header X-Forwarded-Proto $scheme;"""

    config = f"""# Managed Dynamic Site: {domain} -> {upstream_target}
# Generated by CloudWAF Auto-Routing Engine on {datetime.now().isoformat()}

server {{
    listen 8080;
    server_name {domain};

    access_log /var/log/nginx/access.json json_combined;
    error_log /var/log/nginx/error.log warn;
    include /etc/nginx/includes/captcha_server.conf;
    include /etc/nginx/includes/otp_server.conf;

    modsecurity on;
    modsecurity_transaction_id "$request_id";

    # Static Assets bypass rate limiting
    location ~* \\.(?:css|js|jpg|jpeg|png|gif|ico|svg|webp|woff|woff2|ttf|json|map)$ {{
        proxy_pass {upstream_target};
        proxy_set_header Host {host_header};
{ssl_directives}
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header X-Real-IP $waf_client_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
    }}

    location / {{
        mirror /internal-ml-capture;
        mirror_request_body on;

        auth_request /internal-shield-check;
        auth_request_set $retry_after $upstream_http_retry_after;
        auth_request_set $shield_type $upstream_http_x_shield_type;

        proxy_pass {upstream_target};
        proxy_set_header Host {host_header};
{ssl_directives}
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header X-Real-IP $waf_client_ip;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_redirect off;
        proxy_buffering off;
    }}

    location = /internal-rate-limit {{
        internal;
        proxy_method GET;
        proxy_pass http://host.docker.internal:8000/api/limiter/check;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        # $waf_client_ip: real visitor IP, header trusted only from our own
        # proxies (geo in nginx/templates/conf.d/default.conf.template). The
        # limiter keys on the first X-Forwarded-For entry, so send only that.
        proxy_set_header X-Real-IP $waf_client_ip;
        proxy_set_header X-Forwarded-For $waf_client_ip;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Host $host;
    }}

    error_page 401 =429 @rate_limit_exceeded;
    location @rate_limit_exceeded {{
        add_header Retry-After $retry_after always;
        add_header Content-Type text/plain always;
        return 429 "Too Many Requests. Rate limit exceeded. Please try again later.";
    }}

    error_page 403 /403.html;
    location = /403.html {{ root /usr/share/nginx/html; internal; }}
}}
"""
    return config


def deploy_site_route(domain_name: str, origin: Dict[str, Any]) -> bool:
    domain = _safe_domain(domain_name)
    filename = f"site-{domain}.conf"
    config_content = generate_site_nginx_config(domain, origin)

    # 1. Write persistent copy on host
    host_file = PERSISTENT_SITES_DIR / filename
    host_file.write_text(config_content, encoding="utf-8")

    # 2. Write into nginx container /etc/nginx/conf.d/
    container_path = f"/etc/nginx/conf.d/{filename}"
    # tee with an argument list -- no shell, so the path is never interpreted.
    write_cmd = ["docker", "exec", "-i", CONTAINER_NAME, "tee", container_path]
    res = subprocess.run(write_cmd, input=config_content.encode("utf-8"), capture_output=True)
    if res.returncode != 0:
        logger.error(f"Failed to write config into nginx container: {res.stderr.decode()}")
        return False

    # 3. Test nginx config (Safety Net!)
    try:
        rule_mgr.test_nginx()
    except Exception as e:
        logger.error(f"Nginx test failed for site {domain}, rolling back: {e}")
        subprocess.run(["docker", "exec", CONTAINER_NAME, "rm", "-f", container_path], capture_output=True)
        if host_file.exists():
            host_file.unlink()
        raise RuntimeError(f"Nginx configuration test failed: {e}")

    # 4. Reload nginx (Zero Downtime)
    try:
        rule_mgr.reload_nginx()
        logger.info(f"Successfully deployed and reloaded route for {domain}")
    except Exception as e:
        logger.error(f"Failed to reload nginx for site {domain}: {e}")
        return False

    # 5. Activate Origin in DynamoDB if currently pending
    origin_id = origin.get("id")
    if origin_id:
        now = datetime.now().isoformat() + "Z"
        db.update_origin(origin_id, {"status": "active", "updated_at": now})
        logger.info(f"Origin {origin_id} marked as ACTIVE")

    return True


def remove_site_route(domain_name: str) -> bool:
    domain = _safe_domain(domain_name)
    filename = f"site-{domain}.conf"
    host_file = PERSISTENT_SITES_DIR / filename
    if host_file.exists():
        host_file.unlink()

    container_path = f"/etc/nginx/conf.d/{filename}"
    subprocess.run(["docker", "exec", CONTAINER_NAME, "rm", "-f", container_path], capture_output=True)

    try:
        rule_mgr.test_nginx()
        rule_mgr.reload_nginx()
        logger.info(f"Removed route for {domain}")
        return True
    except Exception as e:
        logger.error(f"Failed to reload nginx after removing {domain}: {e}")
        return False


def sync_all_verified_sites() -> int:
    """Scan all verified domains in DynamoDB and deploy their configs."""
    try:
        domains = db.domains_table.scan().get("Items", [])
        origins_list = db.origins_table.scan().get("Items", [])
        origins_by_id = {o["id"]: o for o in origins_list}

        deployed_count = 0
        for d in domains:
            if d.get("dns_verified") and d.get("origin_id"):
                origin = origins_by_id.get(d["origin_id"])
                if origin and not origin.get("is_tunnel"):
                    domain_name = d.get("domain_name")
                    if domain_name:
                        logger.info(f"Auto-syncing route for {domain_name} -> {origin.get('ip')}:{origin.get('port')}")
                        if deploy_site_route(domain_name, origin):
                            deployed_count += 1
        return deployed_count
    except Exception as e:
        logger.error(f"Failed to sync verified sites: {e}")
        return 0