import os
import json
import logging
import httpx
from pathlib import Path
from typing import Dict, Any
from services.rule_manager import RuleManager

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
SETTINGS_FILE = DATA_DIR / "system_settings.json"

DEFAULT_SETTINGS = {
    "waf_mode": "blocking",                      # "blocking" or "detection_only"
    "paranoia_level": 1,                         # 1 to 4
    "inbound_anomaly_threshold": 10,             # default CRS inbound limit
    "outbound_anomaly_threshold": 10,            # default CRS outbound limit
    "auto_purge_edge_cache": True,               # purge cache on rule update
    "real_ip_header": "X-Forwarded-For",         # header for client IP extraction
    "telegram_notifications": True,
    "telegram_bot_token": os.getenv("TELEGRAM_BOT_TOKEN", ""),
    "telegram_chat_id": os.getenv("TELEGRAM_CHAT_ID", ""),
    "edge_sync_interval_seconds": 5,
}


class SettingsService:
    def __init__(self):
        self.rule_manager = RuleManager()
        self._ensure_settings_file()

    def _ensure_settings_file(self):
        if not SETTINGS_FILE.exists():
            SETTINGS_FILE.write_text(json.dumps(DEFAULT_SETTINGS, indent=2), encoding="utf-8")

    def get_settings(self) -> Dict[str, Any]:
        self._ensure_settings_file()
        try:
            raw_data = json.loads(SETTINGS_FILE.read_text(encoding="utf-8"))
            # Filter only valid keys in DEFAULT_SETTINGS
            data = {k: raw_data.get(k, v) for k, v in DEFAULT_SETTINGS.items()}
            # Mask secret tokens before returning to UI
            masked = dict(data)
            token = masked.get("telegram_bot_token", "")
            if token and len(token) > 8:
                masked["telegram_bot_token_masked"] = f"{token[:4]}...{token[-4:]}"
            else:
                masked["telegram_bot_token_masked"] = ""
            return masked
        except Exception as e:
            logger.error(f"Error reading settings: {e}")
            return DEFAULT_SETTINGS

    def update_settings(self, new_settings: Dict[str, Any]) -> Dict[str, Any]:
        current = self.get_settings()
        for k, v in new_settings.items():
            if k in DEFAULT_SETTINGS:
                # If secret token was sent empty, keep old token unless explicitly set
                if k == "telegram_bot_token" and (not v or v.startswith("***") or "..." in v):
                    continue
                current[k] = v

        # Write to JSON
        clean_save = {k: v for k, v in current.items() if not k.endswith("_masked")}
        SETTINGS_FILE.write_text(json.dumps(clean_save, indent=2), encoding="utf-8")

        # Sync ModSecurity configuration override if WAF mode changed
        self._apply_modsecurity_settings(clean_save)

        return self.get_settings()

    def _apply_modsecurity_settings(self, settings: Dict[str, Any]):
        """Write modsecurity-override.conf to dynamically update SecRuleEngine and CRS thresholds."""
        try:
            override_dir = Path(__file__).resolve().parent.parent.parent.parent / "modsecurity" / "custom-rules"
            override_file = override_dir / "00-modsecurity-override.conf"
            
            engine_val = "On" if settings.get("waf_mode") == "blocking" else "DetectionOnly"
            paranoia = settings.get("paranoia_level", 1)
            inbound = settings.get("inbound_anomaly_threshold", 10)
            outbound = settings.get("outbound_anomaly_threshold", 10)

            content = (
                f"# Dynamic Settings Override (Generated by CloudWAF Control Plane)\n"
                f"SecRuleEngine {engine_val}\n"
                f"SecAction \\\n"
                f" \"id:900000,\\\n"
                f"  phase:1,\\\n"
                f"  nolog,\\\n"
                f"  pass,\\\n"
                f"  t:none,\\\n"
                f"  setvar:tx.paranoia_level={paranoia},\\\n"
                f"  setvar:tx.inbound_anomaly_score_threshold={inbound},\\\n"
                f"  setvar:tx.outbound_anomaly_score_threshold={outbound}\"\n"
            )
            override_file.write_text(content, encoding="utf-8")
            self.rule_manager.reload_nginx()
        except Exception as e:
            logger.warning(f"Failed to apply dynamic ModSecurity override: {e}")

    async def send_test_notification(self, channel: str = "telegram") -> Dict[str, Any]:
        settings = self.get_settings()
        if channel == "telegram":
            bot_token = settings.get("telegram_bot_token")
            chat_id = settings.get("telegram_chat_id")
            if not bot_token or not chat_id:
                raise ValueError("Telegram Bot Token and Chat ID must be configured first")

            url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
            msg = (
                "🛡️ *CloudWAF Test Alert*\n\n"
                "✅ Integration verified successfully!\n"
                "Your alert channel is active and ready to receive real-time threat notifications."
            )
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.post(url, json={
                    "chat_id": chat_id,
                    "text": msg,
                    "parse_mode": "Markdown"
                })
                if resp.status_code == 200:
                    return {"status": "success", "message": "Test alert sent to Telegram successfully"}
                else:
                    raise RuntimeError(f"Telegram API error: {resp.text}")

        raise ValueError(f"Unknown alert channel: {channel}")
