# WAF Zero-Trust Tunnel Agent Configuration File
# -----------------------------------------------

# The token identifying this customer origin server (retrieved from Dashboard)
WAF_TOKEN="3c400818-b11f-4f4c-bd65-988b2c8360cc"

# WAF Control Panel Backend API URL
WAF_BACKEND_URL="http://localhost:8000"
