#!/usr/bin/env python3
"""WAF Config Sync Script
Fetches rules from Dashboard API and syncs them to Edge Nodes (SG/JP/TH),
then triggers nginx reload on each edge container.

Usage:
  python scripts/sync_waf_rules.py --token <JWT_TOKEN>
  python scripts/sync_waf_rules.py --token <JWT_TOKEN> --dry-run
"""
import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
import re
from pathlib import Path

import httpx

# ── Config ──────────────────────────────────────────────────────────────────
DASHBOARD_API = os.getenv("DASHBOARD_API", "http://localhost:8000")

EDGE_CONTAINERS = {
    "SG": os.getenv("CDN_SG_CONTAINER", "cdn-edge-sg"),
    "JP": os.getenv("CDN_JP_CONTAINER", "cdn-edge-jp"),
    "TH": os.getenv("CDN_TH_CONTAINER", "cdn-edge-th"),
}

EDGE_RULES_PATH = os.getenv("EDGE_RULES_PATH", "/opt/custom-rules/dashboard-sync.conf")
LOCAL_RULES_DIR = Path(__file__).parent.parent / "modsecurity" / "custom-rules"
SYNC_CONF_FILE = LOCAL_RULES_DIR / "dashboard-sync.conf"
SYNC_LOG_FILE = LOCAL_RULES_DIR / "sync.log"


ALLOWED_VARIABLES = {"REQUEST_URI", "ARGS", "REQUEST_HEADERS", "REQUEST_BODY"}
ALLOWED_ACTIONS = {"BLOCK", "CHALLENGE", "DECEIVE"}
ALLOWED_SEVERITIES = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "ERROR", "WARNING", "NOTICE"}


# ── Rule Formatter ──────────────────────────────────────────────────────────
def escape_secrule_string(value: str, quote_char: str) -> str:
    """Escape a value for safe embedding inside a ModSecurity SecRule quoted field."""
    return str(value).replace("\\", "\\\\").replace(quote_char, "\\" + quote_char)


def rules_to_modsecurity_conf(rules: list) -> str:
    """Convert rule dicts to ModSecurity SecRule directives."""
    ts = datetime.utcnow().isoformat() + "Z"
    lines = [
        "# WAF Custom Rules — Auto-generated by sync_waf_rules.py",
        f"# Generated at: {ts}",
        f"# Total rules: {len(rules)}",
        "",
    ]
    for rule in rules:
        raw_id = str(rule.get("id", "")).strip()
        rid = raw_id.replace("custom-", "")
        # Skip invalid/non-numeric IDs or dummy files like 00-modsecurity-override
        if not rid or not rid.isdigit():
            continue

        variable = rule.get("variable", "REQUEST_URI")
        if variable == "N/A":
            continue

        operator = rule.get("operator", "@rx .")
        if operator == "N/A":
            continue

        severity = str(rule.get("severity", "HIGH")).upper()
        if severity == "N/A":
            severity = "HIGH"

        message = str(rule.get("message", "Custom rule"))
        if message == "N/A":
            message = "Custom rule"

        action = str(rule.get("action", "BLOCK") or "BLOCK").strip().upper()
        deception_template = str(rule.get("deception_template", "auto") or "auto").strip().lower()

        # Same guards as RuleManager.validate_rule: rules reach this script
        # from the API, but a line break would still break the whole file.
        if variable not in ALLOWED_VARIABLES or action not in ALLOWED_ACTIONS:
            continue
        if any(c in str(operator) + message for c in "\r\n\x00"):
            continue
        if not re.fullmatch(r"[A-Za-z_]{1,32}", deception_template):
            deception_template = "auto"
        if severity not in ALLOWED_SEVERITIES:
            severity = "HIGH"

        safe_operator = escape_secrule_string(operator, '"')
        # msg:'...' sits inside the double-quoted action list: escape both quotes
        safe_message = escape_secrule_string(message, "'").replace('"', '\\"')

        if action == "DECEIVE":
            # Change to phase:1 to run before CRS 949110
            directives = f"id:{rid},phase:1,deny,status:418,tag:'action:deceive'"
            if deception_template and deception_template != "auto":
                directives += f",tag:'template:{deception_template}'"
            directives += f",severity:{severity},log,msg:'{safe_message}'"
        elif action == "CHALLENGE":
            directives = f"id:{rid},phase:2,deny,status:401,tag:'action:challenge',severity:{severity},log,msg:'{safe_message}'"
        else:  # BLOCK (default)
            directives = f"id:{rid},phase:2,deny,status:403,severity:{severity},log,msg:'{safe_message}'"

        lines.append(f'SecRule {variable} "{safe_operator}" \\')
        lines.append(f'    "{directives}"')
        lines.append("")

    return "\n".join(lines)


# ── API ─────────────────────────────────────────────────────────────────────
def fetch_rules(token: str) -> list:
    headers = {"Authorization": f"Bearer {token}"}
    try:
        r = httpx.get(f"{DASHBOARD_API}/api/rules/", headers=headers, timeout=10.0)
        r.raise_for_status()
        return r.json().get("rules", [])
    except httpx.HTTPError as exc:
        print(f"ERROR: Failed to fetch rules: {exc}")
        sys.exit(1)


# ── Local file ──────────────────────────────────────────────────────────────
def write_local_conf(content: str) -> Path:
    LOCAL_RULES_DIR.mkdir(parents=True, exist_ok=True)
    SYNC_CONF_FILE.write_text(content, encoding="utf-8")
    print(f"  Written local conf: {SYNC_CONF_FILE}")
    return SYNC_CONF_FILE


# ── Sync to container ───────────────────────────────────────────────────────
def sync_to_container(region: str, container: str, conf: Path, dry_run: bool) -> dict:
    result = {
        "region": region,
        "container": container,
        "status": "pending",
        "synced_at": None,
        "error": None,
    }
    if dry_run:
        print(f"  [DRY-RUN] {region}: would copy to {container}:{EDGE_RULES_PATH} and reload")
        result["status"] = "dry_run"
        return result

    try:
        # 1. Copy conf into container
        subprocess.run(
            ["docker", "cp", str(conf), f"{container}:{EDGE_RULES_PATH}"],
            check=True, capture_output=True, timeout=15,
        )
        # 2. Test config
        test = subprocess.run(
            ["docker", "exec", container, "nginx", "-t"],
            capture_output=True, timeout=10,
        )
        if test.returncode != 0:
            err = test.stderr.decode().strip()
            raise RuntimeError(f"nginx -t failed: {err}")
        # 3. Reload
        subprocess.run(
            ["docker", "exec", container, "nginx", "-s", "reload"],
            check=True, capture_output=True, timeout=10,
        )
        result["status"] = "synced"
        result["synced_at"] = datetime.utcnow().isoformat() + "Z"
        print(f"  Synced and reloaded {container}")

    except subprocess.CalledProcessError as exc:
        msg = exc.stderr.decode().strip() if exc.stderr else str(exc)
        result["status"] = "failed"
        result["error"] = msg
        print(f"  ERROR {region}: {msg}")
    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        print(f"  ERROR {region}: {exc}")

    return result


# ── Sync log ────────────────────────────────────────────────────────────────
def write_sync_log(results: list) -> None:
    SYNC_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    entry = {"timestamp": datetime.utcnow().isoformat() + "Z", "results": results}
    with open(SYNC_LOG_FILE, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry) + "\n")
    print(f"  Sync log: {SYNC_LOG_FILE}")


# ── Main ────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Sync WAF rules to Edge Nodes")
    parser.add_argument("--token", required=True, help="Bearer JWT token from Dashboard")
    parser.add_argument("--dry-run", action="store_true", help="Preview only — no writes or reloads")
    args = parser.parse_args()

    print("=" * 50)
    print("WAF Config Sync — Starting")
    print("=" * 50)

    print("\n[1] Fetching rules from Dashboard API...")
    rules = fetch_rules(args.token)
    print(f"    {len(rules)} rules fetched")

    if not rules:
        print("No rules to sync. Exiting.")
        sys.exit(0)

    print("\n[2] Generating ModSecurity conf...")
    conf_path = write_local_conf(rules_to_modsecurity_conf(rules))

    print("\n[3] Syncing to edge containers...")
    results = []
    for region, container in EDGE_CONTAINERS.items():
        print(f"\n  => {region} ({container})")
        results.append(sync_to_container(region, container, conf_path, args.dry_run))

    print("\n[4] Writing sync log...")
    write_sync_log(results)

    print("\n" + "=" * 50)
    failed = [r for r in results if r["status"] == "failed"]
    for r in results:
        icon = "OK " if r["status"] in ("synced", "dry_run") else "ERR"
        print(f"  [{icon}] {r['region']}: {r['status']}")

    if failed:
        print(f"\nWARN: {len(failed)} node(s) failed.")
        sys.exit(1)
    print(f"\nAll {len(results)} node(s) synced successfully.")
    sys.exit(0)


if __name__ == "__main__":
    main()
